<div class="content-left fl">

								<div class="breadcrumb grey99 fnt11">
								<?php echo CHtml::link('Home', CController::createUrl("site/index"), array('class' => 'breadcrumb grey99 fnt11')); ?> &#x21d2;
								Disclaimer
								</div>
								
                     <div class="page-title mt10 bdrbtm">
                        <h2 class="page-title-block fl">Disclaimer</h2>
                        <div class="share-elements fr">
                         <div class="fb-like" data-href="http://www.facebook.com/artistaloud" data-send="false" data-layout="button_count" data-width="110" data-show-faces="false" data-font="tahoma"></div>
                        
                        </div>
                    <div class="clr"></div>
                    </div>

                   
                    <div class="news-content grey99">
                    <p><span class="white"><strong>Disclaimer of Warranties and Limitation of Liability</strong></span></p>
                   
                   <p>This site and all information, content, materials, products (including software) and services included on or otherwise made available to you through this site are provided by Hungama Digital Entertainment Media Private Limited (hereinafter referred to as "<span class="white"><strong>Hungama</strong></span>", "<span class="white"><strong>we</strong></span>" and/or "<span class="white"><strong>us</strong></span>") on an "as is" and "as available" basis, unless otherwise specified in writing. Hungama makes no representations or warranties of any kind, express or implied, as to the operation of this site or the information, content, materials, products (including software) or services included on or otherwise made available to you through this site, unless otherwise specified in writing. You expressly agree that your use of this site is at your sole risk.</p>

<p>To the full extent permissible by applicable law, Hungama disclaims all warranties, express or implied, including, but not limited to, implied warranties of merchantability and fitness for a particular purpose. Hungama does not warrant that this site; information, content, materials, products (including software) or services included on or otherwise made available to you through this site; their servers are free of viruses or other harmful components. Hungama will not be liable for any damages of any kind arising from the use of this site or from any information, content, materials, products (including software) or services included on or otherwise made available to you through this site, including, but not limited to direct, indirect, incidental, punitive, and consequential damages, unless otherwise specified in writing.</p>

<p>Hungama makes no representation or warranty that any material, content, products or services displayed on or offered through the service are accurate, complete, appropriate, reliable, or timely. We also make no representations or warranties that the service will meet your requirements and/or your access to and use of the service will be uninterrupted or error-free, free of viruses, malicious code, or other harmful components, or otherwise secure. Some jurisdictions do not allow the exclusion of certain warranties. Accordingly, some of the above exclusions may not apply to you.</p>

<p>You agree that your use of the website shall be at your sole risk. To the fullest extent permitted by law, Hungama, its officers, directors, employees, and agents disclaim all warranties, express or implied, in connection with the website and your use thereof. Hungama makes no warranties or representations about the accuracy or completeness of this site's content or the content of any sites linked to this site and assumes no liability or responsibility for any (i) errors, mistakes, or inaccuracies of content, (ii) personal injury or property damage, of any nature whatsoever, resulting from your access to and use of our website, (iii) any unauthorized access to or use of our secure servers and/or any and all personal information and/or financial information stored therein, (iv) any interruption or cessation of transmission to or from our website, (iv) any bugs, viruses, trojan horses, or the like which may be transmitted to or through our website by any third party, and/or (v) any errors or omissions in any content or for any loss or damage of any kind incurred as a result of the use of any content posted, emailed, transmitted, or otherwise made available via the website. Hungama does not warrant, endorse, guarantee, or assume responsibility for any product or service advertised or offered by a third party through the website or any hyperlinked website or featured in any banner or other advertising, and Hungamawill not be a party to or in any way be responsible for monitoring any transaction between you and third-party providers of products or services. As with the purchase of a product or service through any medium or in any environment, you should use your best judgment and exercise caution where appropriate.</p>

<p>Inclusion of any linked website on the website does not imply approval or endorsement of the linked website by Hungama. When you access these third-party sites, you do so at your own risk. Hungama takes no responsibility for third party advertisements which are posted on the website or through the services, nor does it take any responsibility for the goods or services provided by its advertisers. Hungama is not responsible for the conduct, whether online or offline, of any user of the services. Hungama assumes no responsibility for any error, omission, interruption, deletion, defect, delay in operation or transmission, communications line failure, theft or destruction or unauthorized access to, or alteration of, any user or member communication. Hungama is not responsible for any problems or technical malfunction of any telephone network or lines, computer online systems, servers or providers, computer equipment, software, failure of any email or players due to technical problems or traffic congestion on the internet or on any of the services or combination thereof, including any injury or damage to users or to any person's computer related to or resulting from participation in connection with the services. Under no circumstances shall Hungama be responsible for any loss or damage, including personal injury or death, resulting from use of the services, attendance at a Hungama event, from any content posted on or through the services, or from the conduct of any users of the services, whether online or offline. The services are provided "as-is" and as available and Hungama expressly disclaims any warranty of fitness for a particular purpose or non-infringement. Hungama cannot guarantee and does not promise any specific results from use of the services.</p>

<p>Hungama disclaims all Intellectual Property Rights ("<span class="white"><strong>IPR</strong></span>") vested in imageries which have been directly downloaded from the internet platforms or which have been used from open source platforms. Hungama's IPRs remain restricted to the modifications, innovations, alterations, if any in the presentation style and graphical representation made with reference to the said imageries. All copyrights vested in the original imagery are the proprietary ownership and are assumed under the Copyright Laws to be in possession with the respective artists/ authors who have created such imageries. Such ownership rights vest in the artists/authors right from the date of conceptualization of such imagery. Hungama disclaims all rights which vest in the authors/ artists responsible for creation of the imagery.</p>

                    </div>
                    
             
                    
            	</div>